[build]
  command = "npm run build"
  publish = ".next"

# Enable the Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Ensure API routes work correctly
[functions]
  included_files = [".next/standalone/**"]

# Environment variable to disable ESLint during build
[build.environment]
  DISABLE_ESLINT_PLUGIN = "true"
